vscode:
  extensions:
    - esbenp.prettier-vscode@2.2.2:KF7uv+/v78QclIpOv6wh6g==
    - xabikos.JavaScriptSnippets@1.7.2:XXmiw8r7K3Guifex/E73aQ==
    - dbaeumer.vscode-eslint@1.9.1:YVcwmzKVVl+zZ+wMB02GjQ==
    - dsznajder.es7-react-js-snippets@2.4.3:hx3eTJAy1EbZG5qQ6lxrdA==
    - formulahendry.auto-close-tag@0.5.6:oZ/8R2VhZEhkHsoeO57hSw==
    - ritwickdey.live-sass@3.0.0:x2c+sCJm+QmH2qn2h1X9Zw==